version: 2
jobs:
  build:
    docker:
      - image: yeongsheng/alpine-elixir-circleci:latest
      # - image: circleci/node:latest
      # - image: circleci/elixir:latest
      # - image: postgres:9.6.2
      #   environment:
      #     POSTGRES_DB: hello_phoenix_test
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres

    working_directory: /home/circleci/hello_phoenix
    # working_directory: ~/hello_phoenix
    environment:
      # - PATH: "$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"
      - MIX_ENV: test
    #   - HOME: "/home/circleci"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8" # rsa sha256
            - "SHA256:br9IjFspm1vxR3iA35FWE+4VTyz1hYVLIE2t1/CeyWQ" # dsa sha256
            - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48" # rsa
            - "ad:1c:08:a4:40:e3:6f:9c:f5:66:26:5d:4b:33:5d:8c" # dsa
      - run: echo $HOME
      #     name: Setting environment variables
      #     environment:
      #       HOME: /home/circleci/hello_phoenix
      #     command: checkout
      - checkout
      - run: echo "hello world"

# machine:
  # environment:
  #   PATH: "$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"
#     MIX_ENV: test
#
# dependencies:
#   pre:
#     - if ! asdf | grep version; then git clone https://github.com/asdf-vm/asdf.git ~/.asdf; fi
#     - asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git || true
#     - asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git || true
#     - asdf install
#     - mix local.hex --force
#     - mix local.rebar --force
#   override:
#     - mix deps.get
#   cache_directories:
#     - ~/.asdf
#     - ~/.mix
#     - deps
#     - _build
#
# test:
#   override:
#     - mix ecto.create
#     - mix ecto.migrate
#     - mix espec
