version: 2
jobs:
  build:
    docker:
      - image: yeongsheng/alpine-elixir-circleci:latest
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    environment:
      - MIX_ENV: test
    steps:
      - checkout

      - run:
          command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
          background: true

      - restore_cache:
          keys:
            - v1-myapp-deps-{{ checksum "mix.exs" }}
            - v1-myapp-deps-

      - run: mix deps.get

      - save_cache:
          key: v1-myapp-deps-{{ checksum "mix.exs" }}
          paths:
            - ~/CIRCLE_PROJECT_REPONAME/deps

      - restore_cache:
          keys:
            - v1-myapp-build-{{ checksum "mix.exs" }}
            - v1-myapp-build-

      - run: mix deps.compile

      - save_cache:
          key: v1-myapp-build-{{ checksum "mix.exs" }}
          paths:
            - ~/CIRCLE_PROJECT_REPONAME/_build

      - run: mix ecto.create

      - run: mix ecto.migrate

      - run: mix espec

# machine:
  # environment:
  #   PATH: "$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"
#     MIX_ENV: test
#
# dependencies:
#   pre:
#     - if ! asdf | grep version; then git clone https://github.com/asdf-vm/asdf.git ~/.asdf; fi
#     - asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git || true
#     - asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git || true
#     - asdf install
#     - mix local.hex --force
#     - mix local.rebar --force
#   override:
#     - mix deps.get
#   cache_directories:
#     - ~/.asdf
#     - ~/.mix
#     - deps
#     - _build
#
# test:
#   override:
#     - mix ecto.create
#     - mix ecto.migrate
#     - mix espec
